# Project Information
site_name: Hrbust_ACM's Wiki
site_description: Hrbust_ACM's Wiki
site_author: Hrbust_Acmer
site_url: https://hrbust-acm.online
strict: true

# Repository
repo_name: 'acm-hrbust-wiki/wiki'
repo_url: 'https://github.com/acm-hrbust-wiki/wiki/tree/master'
edit_uri: 'docs/'

nav:
  - 首页:
    - Getting Started: index.md
    - Wiki介绍: home.md
    - 如何使用: faq.md
    # - MarkDown模板: markdown-model.md
  # - 算法基础:
  #   - 算法基础简介: Base/index.md
  #   - 排序:
  #     - 快速排序: Base/sort/快速排序.md
  #     - 归并排序: Base/sort/归并排序.md
  #   - 枚举: Base/枚举.md
  #   - 贪心: Base/贪心.md
  - 搜索:
    # - 搜索部分简介: Search/index.md
    - 深度优先搜索: Search/DFS.md
    - 广度优先搜索: Search/BFS.md
    - 双向搜索: Search/DeSearch.md
    - 记忆化搜索: Search/Memory_Search.md
    - 极大极小化搜索: Search/极大极小搜索-alpha-beta剪枝.md
  - 动态规划:
    # - 动态规划部分简介: DP/index.md
    - 状态压缩DP: DP/状压DP.md
    - 树形 DP: DP/树形DP.md
    - 区间 DP: DP/区间DP.md
    - 数位 DP: DP/数位DP.md
    - 概率 DP: DP/概率DP.md
    - 期望 DP: DP/期望DP.md  
  - 数据结构: 
    # - 数据结构部分简介: Data_Structure/index.md
    - 一维树状数组: Data_Structure/树状数组1.md
    - 二维树状数组: Data_Structure/树状数组2.md
    - ST表: Data_Structure/ST.md
    - RMQ: Data_Structure/RMQ.md
    - 线段树:
      - 线段树lazy标记: Data_Structure/线段树lazy.md
      - 线段树区间合并: Data_Structure/线段树区间合并.md
      - 扫描线: Data_Structure/扫描线.md
    - 树链剖分:
      - 点剖: Data_Structure/点刨.md
      - 边剖: Data_Structure/边剖.md
    - 分块算法: Data_Structure/分块.md
    - 莫队算法: Data_Structure/莫队.md
    - 点分治: Data_Structure/点分治.md
  - 图论:
    - 二分图:
      - 匈牙利算法: Graph/匈牙利算法.md
      - KM 算法: Graph/KM算法.md
    - 网络流:
      - EK 算法: Graph/EK.md
      - Dinic+当前弧优化: Graph/Dinic.md
      - ISAP算法: Graph/ISAP.md
    - 费用流:
      - SPFA 费用流: Graph/SPFA费用流.md
    # - 拓扑排序: Graph/拓扑排序.md
    # - 最小生成树: Graph/最小生成树.md
  # - 数论:
  #   # - 数论部分简介: Math/index.md
  - 字符串:
    # - 字符串部分简介: String/index.md
    - 字典树: String/字典树.md
    - AC自动机: String/AC自动机.md

  - 计算几何:
    # - 计算几何部分简介: Geometry/index.md
    - 点积叉积的运用: Geometry/点积叉积的运用.md
    - 凸包的求取: Geometry/凸包的求取.md
    - 半平面交: Geometry/半平面交.md
    - 旋转卡壳: Geometry/旋转卡壳.md
  - 附录:
    # - 其他部分简介: Others/index.md
    - 时间/空间复杂度: Others/Time.md
    - 习题: Others/exem.md


# Theme
theme:
  name: material
  language: 'zh'
  palette:
    primary: 'red'
    accent: 'blue'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true  # 横向导航
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Customization
extra:
  search:
    language: 'jp'
  # disqus: 'acm-hrbust-wiki'
  # copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  # pagetime: 'on'
  # manifest: 'manifest.webmanifest'
  # githash: ''

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde