# Project Information
site_name: Hrbust_ACM's Wiki
site_description: Hrbust_ACM's Wiki
site_author: Hrbust_Acmer
site_url: http://acm-hrbust-wiki.github.io
strict: true

# Repository
repo_name: 'acm-hrbust-wiki/acm-hrbust-wiki.github.io'
repo_url: 'https://github.com/acm-hrbust-wiki/acm-hrbust-wiki.github.io'
edit_uri: 'docs/'

nav:
  - 首页:
    - Getting Started: index.md
    - 使用介绍: home.md
  - 算法基础:
    - 算法基础简介: Base/index.md
    - 排序:
      - 快速排序: Base/sort/快速排序.md
      - 归并排序: Base/sort/归并排序.md
    - 枚举: Base/枚举.md
    - 贪心: Base/贪心.md
  - 搜索:
    - 搜索部分简介: Search/index.md
    - DFS: Search/DFS.md
    - BFS: Search/BFS.md
  - 动态规划:
    - 动态规划部分简介: DP/index.md
    - 背包 DP: DP/背包DP.md
    - 区间 DP: DP/区间DP.md
    - 树形 DP: DP/树形DP.md
  - 图论:
    - 图论部分简介: Graph/index.md
    - 拓扑排序: Graph/拓扑排序.md
    - 最小生成树: Graph/最小生成树.md
  - 数据结构:
    - 数据结构部分简介: Data_Structure/index.md
    - 线段树: Data_Structure/线段树.md
    - 树状数组: Data_Structure/树状数组.md
  - 数论:
    - 数论部分简介: Math/index.md
  - 字符串:
    - 字符串部分简介: String/index.md
  - 计算几何:
    - 计算几何部分简介: Geometry/index.md
  - 其他:
    - 其他部分简介: Others/index.md


# Theme
theme:
  name: material
  language: 'zh'
  palette:
    primary: 'red'
    accent: 'blue'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true  # 横向导航
  font:
    text: 'Fira Mono'
    code: 'Fira Mono'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Customization
extra:
  search:
    language: 'jp'
  # disqus: 'acm-hrbust-wiki'
  # copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  # pagetime: 'on'
  # manifest: 'manifest.webmanifest'
  # githash: ''

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde